### ISSUE TITLE
what is build-commit for

### ISSUE THREAD

**Issue by UziTech** [atom-community/atom-ide-template#25]
What is build-commit for? It looks like that builds the `dist` folder and commits it except that the `dist` folder is in `.gitignore` so what exactly does build-commit do?

**Comment by aminya** [comment]
`build-commit` is a workaround for the apm limitation. When you run `npm run build-commit` or `pnpm build-commit`, the project is built, `.gitignore` is disabled temporarily, and the built files are committed to the git history. We need this because apm does not pack the built files similar to how npm does it.

**Comment by UziTech** [comment]
So apm doesn't run the `prepare` script when installing a package?

**Comment by aminya** [comment]
I am not sure. But this is the workaround I have come up with instead of checking in the built files.

We can fix the issue in apm though:
https://github.com/atom/apm/issues/498

**Comment by UziTech** [comment]
After some testing it looks like `prepare` doesn't get called but `postinstall` does. I don't see any disadvantages to just moving the `prepare` script to `postinstall` and we wouldn't need `build-commit` or the `dist` folder checked into the git repo.

**Comment by aminya** [comment]
@UziTech That means you rely on every user's computer to build the typescript and bundle the code. Currently, the dist file is what you built.

**Comment by UziTech** [comment]
Good point
